const data = {
  courses: [
    {
      _id: '1',
      name: 'Python Programming for Beginners',
      category: 'Programming and Development',
      image: '/images/p1.jpeg',
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      description: 'This course is designed to introduce newcomers to the world of programming using Python, one of the most popular and versatile programming languages in the world. Whether you',
    },
    {
      _id: '2',
      name: 'Data Analysis with Python',
      category: 'Data Science and Analytics',
      image: '/images/p2.jpg',
      price: 100,
      countInStock: 20,
      brand: 'Adidas',
      description: 'Unlock the power of data with Python, one of the most popular programming languages for data analysis. This comprehensive course is designed to equip you with the skills needed to explore, analyze',
    },
    {
      _id: '3',
      name: 'Networking Essentials',
      category: 'Networking and Security',
      image: '/images/p3.jpg',
      price: 220,
      countInStock: 0,
      brand: 'Lacoste',
      description: 'The "Networking Essentials" course provides a comprehensive introduction to the fundamental concepts and principles of computer networking. Designed for beginners and those looking to solidify their understanding of network basics, this course covers the key topics necessary to build, maintain, and troubleshoot small to medium-sized networks.',
    },
    {
      _id: '4',
      name: 'Microsoft Azure Fundamentals',
      category: 'Cloud Computing',
      image: '/images/p4.png',
      price: 78,
      countInStock: 15,
      brand: 'Nike',
      description: 'Microsoft Azure Fundamentals is an introductory course designed to provide learners with a foundational understanding of Microsoft Azure, one of the leading cloud computing platforms. This course is ideal for beginners or IT professionals who are new to cloud computing and want to learn the basics of Azure services and architecture.',
    },
    {
      _id: '5',
      name: 'Database Management Systems (DBMS)',
      category: 'Database Management',
      image: '/images/p5.png',
      price: 65,
      countInStock: 5,
      brand: 'Puma',
      description: 'Database Management Systems (DBMS) is a course designed to introduce students to the fundamental concepts, principles, and practices of database management. This course covers the design, development, and management of databases, which are essential for efficiently storing, retrieving, and manipulating data in various applications.',
    },
    {
      _id: '6',
      name: 'Automated Testing with Selenium',
      category: 'Software Testing',
      image: '/images/p6.jpg',
      price: 139,
      countInStock: 12,
      brand: 'Adidas',
      description: 'This course provides a comprehensive introduction to automated software testing using Selenium, one of the most popular open-source tools in the industry. Designed for both beginners and experienced testers, the course covers everything from the basics of automation to advanced testing strategies. Participants will learn how to create, run, and manage automated test scripts to improve the efficiency and effectiveness of their software testing processes.',
    },
  ],
};
export default data;